*** Starting uWSGI 2.0.8 (64bit) on [Sun Dec 28 00:46:17 2014] ***
compiled with version: 4.6.3 on 27 December 2014 02:19:30
os: Linux-3.2.0-29-generic #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012
nodename: a199
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mnyman/.pyenv/versions/synapse-2.7.8/staging/synapse
writing pidfile to project-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/mnyman/.pyenv/versions/synapse-2.7.8/staging/synapse
your processes number limit is 7300
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 194.187.212.199:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:47936 (port auto-assigned) fd 3
Python version: 2.7.3 (default, Feb 27 2014, 20:09:21)  [GCC 4.6.3]
Set PythonHome to /home/mnyman/.pyenv/versions/synapse-2.7.8
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1d72e60
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145536 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/mnyman/.pyenv/versions/synapse-2.7.8/staging/ to pythonpath.
Traceback (most recent call last):
  File "/home/mnyman/.pyenv/versions/synapse-2.7.8/staging/synapse/wsgi.py", line 13, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/home/mnyman/.pyenv/versions/synapse-2.7.8/lib/python2.7/site-packages/django/core/wsgi.py", line 1, in <module>
    from django.core.handlers.wsgi import WSGIHandler
  File "/home/mnyman/.pyenv/versions/synapse-2.7.8/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 6, in <module>
    from io import BytesIO
  File "/home/mnyman/.pyenv/versions/2.7.8/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /home/mnyman/.pyenv/versions/synapse-2.7.8/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS2_Replace
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28890)
spawned uWSGI worker 1 (pid: 28916, cores: 1)
spawned uWSGI http 1 (pid: 28917)
--- no python application found, check your startup logs for errors ---
[pid: 28916|app: -1|req: -1/1] 37.219.205.253 () {36 vars in 653 bytes} [Sun Dec 28 00:46:25 2014] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28916|app: -1|req: -1/2] 37.219.205.253 () {36 vars in 653 bytes} [Sun Dec 28 00:50:15 2014] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Sun Dec 28 01:22:53 2014 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
